### ISSUE TITLE
Ändern des Verzeichnisnamens, das zuletzt für Speichern von PDFs genutzt wurde führt zum Crash des Drucks

### ISSUE THREAD

**Issue by simon-huber** [dennisfabri/JAuswertung#17]
Reproduktionsschritte:

1. Über Vorschau PDF speichern in einem Verzeichnis
2. Verzeichnis umbenennen
3. Erneut über die Vorschau PDF speichern

```

Ort: class java.awt.EventDispatchThread
Thread:Thread[#38,AWT-EventQueue-0,6,main]

Fehlermeldung: java.lang.AssertionError: Got unexpected checked exception from SynchronousJFXCaller.call()
StackTrace:
java.lang.AssertionError: Got unexpected checked exception from SynchronousJFXCaller.call()
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showDialog(SynchronousJFXFileChooser.java:102)
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showDialog(SynchronousJFXFileChooser.java:59)
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showSaveDialog(SynchronousJFXFileChooser.java:125)
	at org.lisasp.swing.filechooser.jfx.FileChooserJFX.saveFile(FileChooserJFX.java:122)
	at org.lisasp.swing.filechooser.FileChooserUtils.saveFile(FileChooserUtils.java:81)
	at de.df.jutils.print.JPrintPreview.doSave(JPrintPreview.java:546)
	at de.df.jutils.print.JPrintPreview.lambda$addButtons$1(JPrintPreview.java:234)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Folder parameter must be a valid folder
	at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:239)
	at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:191)
	at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1721)
	at javafx.stage.FileChooser.showDialog(FileChooser.java:396)
	at javafx.stage.FileChooser.showSaveDialog(FileChooser.java:372)
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.lambda$showSaveDialog$2(SynchronousJFXFileChooser.java:125)
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.lambda$showDialog$0(SynchronousJFXFileChooser.java:93)
	at org.lisasp.swing.filechooser.jfx.SynchronousJFXCaller.lambda$call$1(SynchronousJFXCaller.java:127)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

StackTrace 2:
java.lang.AssertionError        at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showDialog
        at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showDialog
        at org.lisasp.swing.filechooser.jfx.SynchronousJFXFileChooser.showSaveDialog
        at org.lisasp.swing.filechooser.jfx.FileChooserJFX.saveFile
        at org.lisasp.swing.filechooser.FileChooserUtils.saveFile
        at de.df.jutils.print.JPrintPreview.doSave
        at de.df.jutils.print.JPrintPreview.lambda$addButtons$1
        at javax.swing.AbstractButton.fireActionPerformed
        at javax.swing.AbstractButton$Handler.actionPerformed
        at javax.swing.DefaultButtonModel.fireActionPerformed
        at javax.swing.DefaultButtonModel.setPressed
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased
        at java.awt.Component.processMouseEvent
        at javax.swing.JComponent.processMouseEvent
        at java.awt.Component.processEvent
        at java.awt.Container.processEvent
        at java.awt.Component.dispatchEventImpl
        at java.awt.Container.dispatchEventImpl
        at java.awt.Component.dispatchEvent
        at java.awt.LightweightDispatcher.retargetMouseEvent
        at java.awt.LightweightDispatcher.processMouseEvent
        at java.awt.LightweightDispatcher.dispatchEvent
        at java.awt.Container.dispatchEventImpl
        at java.awt.Window.dispatchEventImpl
        at java.awt.Component.dispatchEvent
        at java.awt.EventQueue.dispatchEventImpl
        at java.awt.EventQueue$4.run
        at java.awt.EventQueue$4.run
        at java.security.AccessController.doPrivileged
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege
        at java.awt.EventQueue$5.run
        at java.awt.EventQueue$5.run
        at java.security.AccessController.doPrivileged
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege
        at java.awt.EventQueue.dispatchEvent
        at java.awt.EventDispatchThread.pumpOneEventForFilters
        at java.awt.EventDispatchThread.pumpEventsForFilter
        at java.awt.EventDispatchThread.pumpEventsForHierarchy
        at java.awt.EventDispatchThread.pumpEvents
        at java.awt.EventDispatchThread.pumpEvents
        at java.awt.EventDispatchThread.run

Memory usage (heap and non heap):
Init: 662700032, Max: 10536091648, Used: 205077976, Commited: 301989888
Init: 7667712, Max: -1, Used: 93443176, Commited: 106823680
Total mem: 301989888, Free mem: 95006792, Max mem: 10536091648
Systeminformationen:
  install4j.launcherId: 366
  java.specification.version: 21
  javafx.runtime.version: 21.0.1+6
  sun.cpu.isalist: amd64
  sun.jnu.encoding: Cp1252
  java.class.path: C:\Program Files\JAuswertung\.install4j\i4jruntime.jar;C:\Program Files\JAuswertung\.\libs\alphaserver-api-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\alphaserver-server-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\aopalliance-repackaged-3.0.5.jar;C:\Program Files\JAuswertung\.\libs\checker-qual-3.33.0.jar;C:\Program Files\JAuswertung\.\libs\cloning-1.10.3.jar;C:\Program Files\JAuswertung\.\libs\commons-codec-1.16.0.jar;C:\Program Files\JAuswertung\.\libs\commons-collections4-4.4.jar;C:\Program Files\JAuswertung\.\libs\commons-compress-1.25.0.jar;C:\Program Files\JAuswertung\.\libs\commons-io-2.15.0.jar;C:\Program Files\JAuswertung\.\libs\commons-lang3-3.13.0.jar;C:\Program Files\JAuswertung\.\libs\commons-math3-3.6.1.jar;C:\Program Files\JAuswertung\.\libs\commons-net-3.3.jar;C:\Program Files\JAuswertung\.\libs\commons-text-1.11.0.jar;C:\Program Files\JAuswertung\.\libs\commons.xmt-1.2.1-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\core-3.5.2.jar;C:\Program Files\JAuswertung\.\libs\curvesapi-1.08.jar;C:\Program Files\JAuswertung\.\libs\dom4j-2.1.4.jar;C:\Program Files\JAuswertung\.\libs\error_prone_annotations-2.18.0.jar;C:\Program Files\JAuswertung\.\libs\failureaccess-1.0.1.jar;C:\Program Files\JAuswertung\.\libs\filechooser-core-1.0.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\filechooser-jfx-1.0.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\flying-saucer-core-9.3.1.jar;C:\Program Files\JAuswertung\.\libs\guava-32.0.1-jre.jar;C:\Program Files\JAuswertung\.\libs\hk2-api-3.0.5.jar;C:\Program Files\JAuswertung\.\libs\hk2-locator-3.0.5.jar;C:\Program Files\JAuswertung\.\libs\hk2-utils-3.0.5.jar;C:\Program Files\JAuswertung\.\libs\httpclient5-5.2.1.jar;C:\Program Files\JAuswertung\.\libs\httpcore5-5.2.jar;C:\Program Files\JAuswertung\.\libs\httpcore5-h2-5.2.jar;C:\Program Files\JAuswertung\.\libs\j2objc-annotations-2.8.jar;C:\Program Files\JAuswertung\.\libs\jackson-annotations-2.16.1.jar;C:\Program Files\JAuswertung\.\libs\jackson-core-2.16.1.jar;C:\Program Files\JAuswertung\.\libs\jackson-databind-2.16.1.jar;C:\Program Files\JAuswertung\.\libs\jackson-datatype-jsr310-2.16.1.jar;C:\Program Files\JAuswertung\.\libs\jackson-module-jakarta-xmlbind-annotations-2.16.1.jar;C:\Program Files\JAuswertung\.\libs\jakarta.activation-api-2.1.0.jar;C:\Program Files\JAuswertung\.\libs\jakarta.annotation-api-2.1.1.jar;C:\Program Files\JAuswertung\.\libs\jakarta.inject-api-2.0.1.jar;C:\Program Files\JAuswertung\.\libs\jakarta.ws.rs-api-3.1.0.jar;C:\Program Files\JAuswertung\.\libs\jakarta.xml.bind-api-4.0.0.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-akeditor-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-ares-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-data-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-dp-extensions-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-io-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-bugreport-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-checks-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-core-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-editor-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-file-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-heats-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-httpserver-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-importexport-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-info-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-input-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-print-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-teammembersscan-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-tipoftheday-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-undoredo-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-upload-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-plugins-zusatzwertung-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-print-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-swing-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-times-extractor-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-veranstaltungswertung-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jauswertung-web-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\javafx-base-21.0.1-win.jar;C:\Program Files\JAuswertung\.\libs\javafx-base-21.0.1.jar;C:\Program Files\JAuswertung\.\libs\javafx-controls-21.0.1-win.jar;C:\Program Files\JAuswertung\.\libs\javafx-controls-21.0.1.jar;C:\Program Files\JAuswertung\.\libs\javafx-graphics-21.0.1-win.jar;C:\Program Files\JAuswertung\.\libs\javafx-graphics-21.0.1.jar;C:\Program Files\JAuswertung\.\libs\javassist-3.29.2-GA.jar;C:\Program Files\JAuswertung\.\libs\jcl-over-slf4j-2.0.9.jar;C:\Program Files\JAuswertung\.\libs\jersey-client-3.1.5.jar;C:\Program Files\JAuswertung\.\libs\jersey-common-3.1.5.jar;C:\Program Files\JAuswertung\.\libs\jersey-entity-filtering-3.1.5.jar;C:\Program Files\JAuswertung\.\libs\jersey-hk2-3.1.5.jar;C:\Program Files\JAuswertung\.\libs\jersey-media-json-jackson-3.1.5.jar;C:\Program Files\JAuswertung\.\libs\jgoodies-common-1.8.1.jar;C:\Program Files\JAuswertung\.\libs\jgoodies-forms-1.9.0.jar;C:\Program Files\JAuswertung\.\libs\jgraphx-4.2.2.jar;C:\Program Files\JAuswertung\.\libs\jsr305-3.0.2.jar;C:\Program Files\JAuswertung\.\libs\jteams-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jul-to-slf4j-2.0.9.jar;C:\Program Files\JAuswertung\.\libs\juniversalchardet-2.4.0.jar;C:\Program Files\JAuswertung\.\libs\jutils-common-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-i18n-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-io-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-plugin-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-print-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-swing-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\jutils-wizard-16.2.3.jar;C:\Program Files\JAuswertung\.\libs\l2fprod-common-buttonbar-7.4.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\l2fprod-common-fontchooser-7.4.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\l2fprod-common-shared-7.4.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\l2fprod-common-tasks-7.4.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\l2fprod-common-totd-7.4.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Program Files\JAuswertung\.\libs\log4j-api-2.21.1.jar;C:\Program Files\JAuswertung\.\libs\log4j-over-slf4j-2.0.9.jar;C:\Program Files\JAuswertung\.\libs\logback-classic-1.4.14.jar;C:\Program Files\JAuswertung\.\libs\logback-core-1.4.14.jar;C:\Program Files\JAuswertung\.\libs\miglayout-core-11.0.jar;C:\Program Files\JAuswertung\.\libs\miglayout-swing-11.0.jar;C:\Program Files\JAuswertung\.\libs\mxparser-1.2.2.jar;C:\Program Files\JAuswertung\.\libs\nrjavaserial-5.2.1.jar;C:\Program Files\JAuswertung\.\libs\objenesis-3.3.jar;C:\Program Files\JAuswertung\.\libs\openpdf-1.3.34.jar;C:\Program Files\JAuswertung\.\libs\osgi-resource-locator-1.0.3.jar;C:\Program Files\JAuswertung\.\libs\poi-5.2.5.jar;C:\Program Files\JAuswertung\.\libs\poi-ooxml-5.2.5.jar;C:\Program Files\JAuswertung\.\libs\poi-ooxml-lite-5.2.5.jar;C:\Program Files\JAuswertung\.\libs\poi-scratchpad-5.2.5.jar;C:\Program Files\JAuswertung\.\libs\radiance-neon-4.5.0.jar;C:\Program Files\JAuswertung\.\libs\radiance-substance-4.5.0.jar;C:\Program Files\JAuswertung\.\libs\radiance-trident-4.5.0.jar;C:\Program Files\JAuswertung\.\libs\simmetrics-core-5.0.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\slf4j-api-2.0.9.jar;C:\Program Files\JAuswertung\.\libs\SparseBitSet-1.3.jar;C:\Program Files\JAuswertung\.\libs\swingbits-1.3.0.jar;C:\Program Files\JAuswertung\.\libs\swingfx-1.0.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\sysout-over-slf4j-1.0.2.jar;C:\Program Files\JAuswertung\.\libs\uistate-0.6.0-SNAPSHOT.jar;C:\Program Files\JAuswertung\.\libs\xmlbeans-5.2.0.jar;C:\Program Files\JAuswertung\.\libs\xmlpull-1.1.3.1.jar;C:\Program Files\JAuswertung\.\libs\xstream-1.4.20.jar;C:\Program Files\JAuswertung\.\.
  sun.awt.enableExtraMouseButtons: true
  java.vm.vendor: Eclipse Adoptium
  sun.arch.data.model: 64
  install4j.exeDir: C:\Program Files\JAuswertung\
  java.vendor.url: https://adoptium.net/
  user.timezone: Europe/Berlin
  java.vm.specification.version: 21
  os.name: Windows 11
  javafx.version: 21.0.1
  user.country: DE
  sun.boot.library.path: c:\program files\jauswertung\jre\bin
  sun.java.command: C:\Program Files\JAuswertung\Launcher.exe
  jdk.debug: release
  sun.cpu.endian: little
  exe4j.unextractedPosition: 0
  user.home: C:\Users\Test
  user.language: de
  java.specification.vendor: Oracle Corporation
  java.version.date: 2023-10-17
  java.home: c:\program files\jauswertung\jre
  file.separator: \
  java.vm.compressedOopsMode: Zero based
  line.separator: 

  java.vm.specification.vendor: Oracle Corporation
  java.specification.name: Java Platform API Specification
  exe4j.moduleName: C:\Program Files\JAuswertung\Launcher.exe
  exe4j.consoleCodepage: cp0
  sun.management.compiler: HotSpot 64-Bit Tiered Compilers
  exe4j.isInstall4j: true
  java.runtime.version: 21.0.1+12-LTS
  user.name: Test
  stdout.encoding: Cp1252
  path.separator: ;
  os.version: 10.0
  java.runtime.name: OpenJDK Runtime Environment
  file.encoding: UTF-8
  java.vm.name: OpenJDK 64-Bit Server VM
  java.vendor.version: Temurin-21.0.1+12
  exe4j.semaphoreName: Local\c:_program_files_jauswertung_launcher.exe0
  install4j.appDir: C:\Program Files\JAuswertung\
  java.vendor.url.bug: https://github.com/adoptium/adoptium-support/issues
  java.io.tmpdir: C:\Users\Test\AppData\Local\Temp\
  java.version: 21.0.1
  user.dir: C:\Program Files\JAuswertung
  os.arch: amd64
  java.vm.specification.name: Java Virtual Machine Specification
  swing.boldMetal: false
  native.encoding: Cp1252
  java.library.path: c:\program files\jauswertung\jre\bin;C:\Users\SimonHuber.I11390\.jdks\temurin-17.0.4.1-1\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Projects\docker-compose;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\gs\gs10.00.0\bin;C:\Program Files\WireGuard\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Program Files\Git\bin;C:\Program Files (x86)\GitExtensions\;C:\Program Files\RedHat\Podman\;C:\Program Files\PowerShell\7\;C:\Users\Test\AppData\Local\Microsoft\WindowsApps;C:\Users\Test\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\Test\AppData\Local\JetBrains\Toolbox\scripts;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
  java.vm.info: mixed mode
  stderr.encoding: Cp1252
  java.vendor: Eclipse Adoptium
  java.vm.version: 21.0.1+12-LTS
  sun.io.unicode.encoding: UnicodeLittle
  java.class.version: 65.0
  exe4j.launchName: C:\Program Files\JAuswertung\Launcher.exe
  install4j.swt: false

Version: JAuswertung 2024 (16.2.3)
```

**Comment by dennisfabri** [comment]
Der Fehler sollte in der Version 16.3.0 beseitigt sein.
